### PR TITLE
Mesh from Spline Node: Output a simple Mesh without any extrusions / bevel / shape

### PR DESCRIPTION
**Pull request by OgierM**
image
image

You could obviously pull this off with an Evaluate Spline Node too, but I think it's rather convenient to have this option here aswell. Just trying out stuff / looks is a bit easier this way.

### CODE REVIEW

**Comment by OmarSquircleArt** [comment]
Not sure I understand, can you give a quick example?

**Comment by OgierM** [comment]
This is what I added:


My intention was making it easier to try out different looks when using the slider, because per default it doesn't go lower than 1 - so to see how that looks you would have to add a small setup with the "Evaluate Splines Node"

In it's self it doesn't allow for any particularly new features, but I think it might be able to speed you up, when trying out different looks. On the other hand - I get that this isn't what this node is designed for and that you probably should use a setup with the evaluate splines node instead.

**Comment by OmarSquircleArt** [comment]
I don't think that it is worth it, and it is—as you said—out of the scope of this node. So I am not exactly in favor of this.

**Comment by OgierM** [comment]
Ok 👍

**Comment by OmarSquircleArt** [comment]
@ogierm That was just my opinion, and I could be wrong. Jacques decides if a feature should be added or not. So if you still think it is worth adding, reopen the pull request until Jacques see it an make a decision.

**Comment by ogierm** [comment]
I'll reopen it if I see myself using it very often

**Pull request closed without merging**
