### PR TITLE
Added Hexagon Grid node

### PR DESCRIPTION
**Pull request by harisreedhar**
hexagonGrid

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
Thanks for picking this up!

I think the grid should be connected though. If the user wishes to have separate cells, one can use one of the separate polygons node. Moreover, that generation algorithm should be added in `animation_nodes/algorithms/mesh_generation`.

**Comment by harisreedhar** [comment]
In sverchok they are using ``bmesh.ops.remove_doubles`` to make connected polygons. But it is very slow to compute.

**Comment by OmarEmaraDev** [comment]
Right. This should be computed directly. Give it a try and if proved too hard, I will look into it.

**Comment by harisreedhar** [comment]
> Right. This should be computed directly. Give it a try and if proved too hard, I will look into it.

I'll try

**Comment by harisreedhar** [comment]
So far, I didn't find any algorithms i can understand. So i'm closing this for now.

**Pull request closed without merging**
