### PR TITLE
Added Quaternion Slerp function

### PR DESCRIPTION
**Pull request by harisreedhar**

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
Update the Quaternion mix node with this function. No need to make it an option, it should be the default.

**Comment by harisreedhar** [comment]
> Update the Quaternion mix node with this function. No need to make it an option, it should be the default.

Updated Quaternion mix code

**Review by OmarEmaraDev — CHANGES_REQUESTED** [review]
This doesn't handle the single case in the Mix Quaternion node. Quaternion mathutils already have a slerp, so you can use that.

**Comment by harisreedhar** [comment]
Updated single case in the Mix Quaternion node

**Comment by OmarEmaraDev** [comment]
Can you confirm that the single and multiple cases yield identical or sufficiently similar results?

**Comment by harisreedhar** [comment]
> Can you confirm that the single and multiple cases yield identical or sufficiently similar results?

There are some mismatch in signs and blender's slerp can't go below or above 0 - 1 range
quat_test

**Comment by harisreedhar** [comment]
The code is opted from [here](https://gitlab.com/bztsrc/slerp-opt)

**Comment by OmarEmaraDev** [comment]
We probably don't need to worry about the sign here, because as a representation of rotation, they are both identical. However, we can't have the [0, 1] limit. So you should probably implement your own single method as well. Maybe put it in utils.math just like the euler method.

**Comment by harisreedhar** [comment]
> We probably don't need to worry about the sign here, because as a representation of rotation, they are both identical. However, we can't have the [0, 1] limit. So you should probably implement your own single method as well. Maybe put it in utils.math just like the euler method.

should i add same copy in utils/math?

**Comment by OmarEmaraDev** [comment]
Yes. Add the same function to utils/math, but as a normal python function, without the Cython stuff.

**Review by OmarEmaraDev — APPROVED** [review]
Looks good. Thanks!

Next time. Setup your editor to add new lines at the end of files.

**Comment by OmarEmaraDev** [comment]
Can you update the CHANGELOG as well? Mentioned in the Changed section that we now slerp for Quaternion mixing.

**Comment by harisreedhar** [comment]
Updated change log

**Pull request merged**
