### PR TITLE
Added isUsed property on Shade Object Smooth node

### PR DESCRIPTION
**Pull request by harisreedhar**
This addition can help to avoid unwanted calculation on every execution.

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
How is this supposed to avoid unwanted calculation on every execution?

**Comment by harisreedhar** [comment]
> How is this supposed to avoid unwanted calculation on every execution?



> How is this supposed to avoid unwanted calculation on every execution?

This option allows users to enable and disable socket. Thus node is only evaluated when socket is enabled. For shade smooth i think it is useful.
smoothShade

**Comment by OmarEmaraDev** [comment]
Sounds reasonable. Can you update the CHANGELOG?

**Comment by harisreedhar** [comment]
> Sounds reasonable. Can you update the CHANGELOG?

Updated

**Review by OmarEmaraDev — APPROVED** [review]
Thanks!

**Pull request merged**
