### PR TITLE
Matrix socket usability improvement

### PR DESCRIPTION
**Pull request by harisreedhar**
Added ``Compose Matrix Node`` invoke button on Matrix socket.

matrix_socket_improvement

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
This is already possible with the W shortcut. Or this something different?


https://user-images.githubusercontent.com/25300994/104807977-9abde780-57eb-11eb-962b-4f82bec900f2.mp4

**Comment by harisreedhar** [comment]
> This is already possible with the W shortcut. Or this something different?
> 20210116-111513.mp4

Yeah it is similar, but for multiple Matrix inputs it saves two clicks.

**Comment by OmarEmaraDev** [comment]
I don't think it is worth it in this case. I would rather keep the socket UI as clean as possible.

**Comment by harisreedhar** [comment]
@OmarEmaraDev Ok

**Pull request closed without merging**
