### PR TITLE
MIDI parser retrieves additionally a list of tempo changes as well as note on and note off in quarter notes

### PR DESCRIPTION
**Pull request by lgmventura**
Solves #1885 

Improved flexibility when working with MIDI files. See the issue description for more info. Some UI improvements could be implemented. I will write a documentation on this.

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
Can you update the pull request with screenshots and examples for your changes?

**Comment by lgmventura** [comment]
Hi, sorry for the late response here, but here we go:
- The data structure Midi Note now has timeOn and timeOff in two different units: seconds and quarter notes. Previously it was only in seconds.
- New data structure MIDITempoEvent in `midi/midi_tempo_event.py`
- ReadMIDIFileNode from `midi_file_reader.py` got a new output "MIDI Tempo Event List"
- MIDINoteInfoNode from `midi_note_info.py` got timeOn and timeOff in both seconds and quarter notes.
- New class MIDINoteInfoNode in new file in `midi_tempo_event_info.py` with following I/O:
  - Input "MIDI Tempo Event"
  - Output "Time in Quarter Note"
  - Output "Time in seconds"
  - Output "Tempo".
  - All these become a list by demand
- New classes MIDITempoEventSocket and MIDINoteListSocket in file `sockets/midi_tempo_event.py`.
- In file `utils/midi.py`, the time in quarter notes is included; the object MIDITempoEvent is added to the list of tempos instead of TempoEventRecord, which didn't include timeInQuarterNotes; a new short function timeInTicksToQuarterNotes was created to convert ticks, which is read out from the midi file, into quarter notes; the class NoteOnRecord has now time in ticks and time in seconds; when a noteOff event is found, the note's start and end time will be stored in seconds and in quarter notes. At the end, the tempos will be also returned alongside with the tracks.

**Comment by lgmventura** [comment]
An example setup is shown here:

Main programme: loading the midi, calling the subprogram and using the tempos to pan the screen accordingly.
https://user-images.githubusercontent.com/16710238/197834327-08314cb4-f4e5-4568-b943-dd2b9b28f47d.png

The second image shows the subprogram only:
https://user-images.githubusercontent.com/16710238/197834710-06549164-257f-4b11-b370-0bcba604d770.png

**Comment by OmarEmaraDev** [comment]
Isn't it the case that each MIDI track may have its own tempo map for MIDI format 2? In that case, the proposed design that cover that situation. Maybe this information should be part of the MIDI track instead. I also don't think we should have a separate data type and socket for tempo events, it doesn't seem worth it.

**Pull request closed without merging**
