### PR TITLE
Add a "Random Boolean" node

### PR DESCRIPTION
**Pull request by kdsin23**

### CODE REVIEW

**Review by OmarEmaraDev — CHANGES_REQUESTED** [review]
Perhaps it would be more useful if we have a probability input. 0 being all false and 1 being all true.

Also, merge upstream and fix the conflicts.

**Comment by kdsin23** [comment]
> Perhaps it would be more useful if we have a probability input. 0 being all false and 1 being all true.
> 
> Also, merge upstream and fix the conflicts.

good idea! i will try

**Comment by OmarEmaraDev** [comment]
One thing you shouldn't do is commit your changes to master in your fork. Create another branch and commit to that instead. Your master should be identical to Jacques' master.

I am currently seeing changes from previous commits, can you fix that?

**Comment by kdsin23** [comment]
> One thing you shouldn't do is commit your changes to master in your fork. Create another branch and commit to that instead. Your master should be identical to Jacques' master.
> 
> I am currently seeing changes from previous commits, can you fix that?

i am sorry for this, i not sure i can fix this, because i am not familar with the github

**Comment by OmarEmaraDev** [comment]
Can you close this and create a new pull request to fix this?

**Review by OmarEmaraDev — APPROVED** [review]
Thanks!

**Pull request merged**
