### PR TITLE
Fix the API changes of gpencil nodes.

### PR DESCRIPTION
**Pull request by 3DSinghVFX**
I have fixed the API changes for Stroke Line Width, Frame Number, and Change Line, now they have data type `int`.

### CODE REVIEW

**Review by OmarEmaraDev — APPROVED** [review]

**Comment by 3DSinghVFX** [comment]
Should we change the name `Stroke Thickness > Offset Line Width or Change Line Width`? This option basically offsets the line width of the strokes.

**Comment by OmarEmaraDev** [comment]
@3DSinghVFX I am not familiar with the option, can you demonstrate that for me or point me in the right direction?

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX I am not familiar with the option, can you demonstrate that for me or point me in the right direction?

Okay. In the Stroke, we can set the _Line Width_. However, if we want to offset the line width of all the strokes per layer that we can do with _the Line Change_ option in the Layers. Is that make sense?

**Comment by OmarEmaraDev** [comment]
I think we can leave it as is, one can think of it as a thickness in the space of the layer which have a thickness itself.

**Comment by 3DSinghVFX** [comment]
Peek 2022-03-26 17-51

**Comment by 3DSinghVFX** [comment]
> I think we can leave it as is, one can think of it as a thickness in the space of the layer which have a thickness itself.

Okay.

**Pull request merged**
