### PR TITLE
IsNone boolean check

### PR DESCRIPTION
**Pull request by s-leger**
Hi,
Is None to check if data path (or any value) is available.

### CODE REVIEW

**Comment by JacquesLucke** [comment]
Maybe we can make this part of the  Compare node?

**Comment by JacquesLucke** [comment]
I could update it to also allow only one input socket.

**Comment by s-leger** [comment]
Great Idea, 
Less nodes, but more powerfull ones.

**Comment by JacquesLucke** [comment]
#590

**Pull request closed without merging**
