### PR TITLE
tesselate triangulate

### PR DESCRIPTION
**Pull request by og76**
this is a very interesting one to work with baricentric (tris) transform. It can help deform mesh cage or lattice or similar, and later for uv's and such

It has all the variants from simple vector or polys to  list of polygons or indices, and bmesh

there is a tricky part of it, that I don't like much, that there are 3 formulas to calc this (besides bmesh that works great)
 I would have included only the first as it is far faster, but somehow is not always accurate in terms of resulting normal (order of indices)

I may have another formula for triangulation later, but we'll see

### CODE REVIEW

**Comment by JacquesLucke** [comment]
will check this a bit later

**Comment by JacquesLucke** [comment]
Is it ok to not have this in the next release? I don't find the time to check the correctness of that much 'indirect code'..

**Comment by og76** [comment]
I'd prefer to have it along with barycentric (and any other that works with tris)
 with it I can do quite some tricks, like mesh/cage deform etc

as for the code, I guess the developer / write execution code can always make it clear what is there in the end 
 plus testing for actual working cases.
 I can make some blends if it's easyer ..

**Comment by JacquesLucke** [comment]
Yes would be nice if you could create some very simple test files for the different scenarios.

**Comment by og76** [comment]
[tesselator.blend1](https://drive.google.com/file/d/0BzzAoBwXO8dsX0J1cUE5NWFROGc/view?usp=sharing)

a quick one for all cases

**Comment by JacquesLucke** [comment]
thx, will check tomorow and merge if everything works :)
Is there a specific reason why you did not call the node an_TriangulatePolygonsNode?

Looks like a lot of options, will see if we really need all of them, but let me check first.

**Comment by JacquesLucke** [comment]
Until then you can start writing documentation for all the other nodes you implemented hehe

**Comment by JacquesLucke** [comment]
Will merge this now. For you mainly :D
I don't think that so many people will use it.. This node is VERY likely to change in the next release.

**Pull request merged**
