### PR TITLE
Vectorized the Switch Node

### PR DESCRIPTION
**Pull request by kdsin23**

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
I really can't review this if your pull requests keep showing old changes. Do you make your edits on Github directly?

**Comment by kdsin23** [comment]
> I really can't review this if your pull requests keep showing old changes. Do you make your edits on Github directly?

sorry, i did it on Github directly. i close this request

**Comment by OmarEmaraDev** [comment]
You workflow for creating pull requests should be as follows. First, set up an upstream remote. (First time only)

```
git remote add upstream git@github.com:JacquesLucke/animation_nodes.git
```
Then to work on a new feature:

```bash
git fetch upstream
git checkout master
git merge upstream/master
git checkout -b name-of-your-branch
# Do your changes and commit
git push --set-upstream name-of-your-branch
```

**Comment by kdsin23** [comment]
> You workflow for creating pull requests should be as follows. First, set up an upstream remote. (First time only)
> 
> ```
> git remote add upstream git@github.com:JacquesLucke/animation_nodes.git
> ```
> 
> Then to work on a new feature:
> 
> ```shell
> git fetch upstream
> git checkout master
> git merge upstream/master
> git checkout -b name-of-your-branch
> # Do your changes and commit
> git push --set-upstream name-of-your-branch
> ```

Thank you for your way!

**Pull request closed without merging**
