### PR TITLE
Frame selected

### PR DESCRIPTION
**Pull request by dragere**
Automaticly frame selected nodes, when adding a frame.
frame-selected

As I have created this branch based on my blender2.8 branch, it depends on #1078, but it can still be reviewed, I think.

### CODE REVIEW

**Comment by OmarSquircleArt** [comment]
Don't create a pull request that depends on another pull request. You should branch from the blender2.8 branch and add the operator again independent of the other pull request.

**Comment by OmarSquircleArt** [comment]
It seems you created the other pull request from the blender2.8 branch. You should always branch when creating a feature like this. In this case, branch from upstream the blender2.8 branch.

**Comment by dragere** [comment]
Yeah, I just learned that, I'm not very experienced with git yet.
If you approve this pr, I will merge it with my 2.8 branch so that it can be merged straight with #1078.

**Comment by dragere** [comment]
Dependencies fixed in #1085

**Pull request closed without merging**
