### PR TITLE
 Add Axis Scale option in Viewer 3D node

### PR DESCRIPTION
**Pull request by 3DSinghVFX**
I have added `XYZ` options for matrices in *Viewer 3D* node. These options allow to choose the axis for drawing.
Screenshot from 2020-08-14 21-00-15

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
I am not sure if that's a good idea. I would rather leave that to the user if the user needed it.

**Comment by 3DSinghVFX** [comment]
> I am not sure if that's a good idea. I would rather leave that to the user if the user needed it.

Omar, by default all the axis are enabled.

**Comment by Gerstmann-Bradley** [comment]
> > I am not sure if that's a good idea. I would rather leave that to the user if the user needed it.
> 
> Omar, by default all the axis are enabled.

Do you mean that, in this update, all axis are enabled by default as in the past?

**Comment by OmarEmaraDev** [comment]
I mean generally. If the user wants to zero some axis, then the user should do that explicitly, we shouldn't do it in the node.

If we want to make it easier to visualizer normals somehow, then we should add an independent drawing method for that. But I don't consider this a good solution.

**Comment by 3DSinghVFX** [comment]
> > > I am not sure if that's a good idea. I would rather leave that to the user if the user needed it.
> > 
> > 
> > Omar, by default all the axis are enabled.
> 
> Do you mean that, in this update, all axis are enabled by default as in the past?

Yes. But you can disable them.
Screenshot from 2020-08-14 21-35-34

**Comment by Gerstmann-Bradley** [comment]
I can see some usage of this in some extreme conditions. Personally speaking having these options makes me stressful, because this is unique for matrices, and such uniqueness seems to highlight the importance of these options, but they aren't that important and will not be frequently used in my opinion. I may fear to click them accidentally somehow.
Is there anyway to hide these options if possible? so that if people want to hide it, they can hide it and otherwise everything will kept as before?

**Comment by 3DSinghVFX** [comment]
> I mean generally. If the user wants to zero some axis, then the user should do that explicitly, we shouldn't do it in the node.
> 
> If we want to make it easier to visualizer normals somehow, then we should add an independent drawing method for that. But I don't consider this a good solution.

> I can see some usage of this in some extreme conditions. Personally speaking having these options makes me stressful, because this is unique for matrices, and such uniqueness seems to highlight the importance of these options, but they aren't that important and will not be frequently used in my opinion. I may fear to click them accidentally somehow.

I also realise that problem.

>Is there anyway to hide these options if possible? so that if people want to hide it, they can hide it and otherwise everything will kept as before?

I think that is not possible.

Okay. I'll close this.

**Comment by OmarEmaraDev** [comment]
We can always move such options to the advanced node settings panel. But even implementation wise, in the common case, you are creating a VBO of size double that of the size of the data that you will actually use for drawing, and that's beside the drawing itself. So the solution seems a bit hacky.

**Comment by 3DSinghVFX** [comment]
> We can always move such options to the advanced node settings panel. 

Okay. I have moved those options to the advanced settings.

> But even implementation wise, in the common case, you are creating a VBO of size double that of the size of the data that you will actually use for drawing, and that's beside the drawing itself. So the solution seems a bit hacky.

Okay.

**Pull request closed without merging**
